#!/usr/bin/env sh
doctoc --github README.md

# Remove 'lt' from summary URLS
sed -i 's/-lt/-/g' README.md
# Recover in docs options
sed -i 's/--e /--lte /g' README.md

# Remove 'gt' from summary URLS
sed -i 's/gt)/)/g' README.md
sed -i 's/gt-/-/g' README.md
