#!/usr/bin/env bash
set -eu

which doctoc > /dev/null || {
  echo "requires to have https://www.npmjs.com/package/doctoc installed, either globally or just in this repo"
  echo "(it is not installed as a dev dependency as the use made of it is not worth the subdependencies maintainance)"
  exit 1
}

doctoc --github README.md

# Remove 'lt' and 'gt' from summary URLS
sed -i -E '25,54 s/#(.*)-lt(.*)gt\)$/#\1-\2)/' README.md
sed -i -E '25,54 s/#(.*)gt-lt/#\1/' README.md
sed -i -E '25,54 s/ltkeygt/key/' README.md
